/** Popular places worldwide (romanized; picker display) */
export const POPULAR_REGIONS = [
  // Seoul districts
  'Gangnam-gu',
  'Gangdong-gu',
  'Gangbuk-gu',
  'Gangseo-gu',
  'Gwanak-gu',
  'Gwangjin-gu',
  'Guro-gu',
  'Geumcheon-gu',
  'Nowon-gu',
  'Dobong-gu',
  'Dongdaemun-gu',
  'Dongjak-gu',
  'Mapo-gu',
  'Seodaemun-gu',
  'Seocho-gu',
  'Seongdong-gu',
  'Seongbuk-gu',
  'Songpa-gu',
  'Yangcheon-gu',
  'Yeongdeungpo-gu',
  'Yongsan-gu',
  'Eunpyeong-gu',
  'Jongno-gu',
  'Jung-gu',
  'Jungnang-gu',
  'Suwon',
  'Seongnam',
  'Goyang',
  'Yongin',
  'Bucheon',
  'Ansan',
  'Anyang',
  'Busan',
  'Daegu',
  'Incheon',
  'Gwangju',
  'Daejeon',
  'Ulsan',
  'Jeju',

  // Global cities
  'Los Angeles',
  'New York',
  'Chicago',
  'San Francisco',
  'Seattle',
  'Boston',
  'Tokyo',
  'Osaka',
  'Kyoto',
  'Fukuoka',
  'Sapporo',
  'Beijing',
  'Shanghai',
  'Shenzhen',
  'Guangzhou',
  'Chengdu',
  'Bangkok',
  'Hanoi',
  'Ho Chi Minh City',
  'Singapore',
  'Manila',
  'Jakarta',
  'London',
  'Paris',
  'Berlin',
  'Madrid',
  'Barcelona',
  'Rome',
  'Vancouver',
  'Toronto',
  'Montreal',
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Dubai',
  'Tel Aviv',
  'Istanbul',
];
