/* Auto-generated by scripts/gen-common-i18n.mjs */
import type { AppLanguage } from '@/utils/languageStorage';

export type CommonMessageKey =
  | 'disputeBanner'
  | 'ok'
  | 'statTrades'
  | 'statShares'
  | 'statDisputes';

const COMMON_MESSAGES: Record<AppLanguage, Record<CommonMessageKey, string>> = {
  en: {
    disputeBanner: 'The other party opened a dispute. Please review.',
    ok: 'OK',
    statTrades: 'Trades',
    statShares: 'Shares',
    statDisputes: 'Disputes',
  },
  ko: {
    disputeBanner: '상대방이 분쟁을 열었습니다. 확인해 주세요.',
    ok: '확인',
    statTrades: '거래',
    statShares: '나눔',
    statDisputes: '분쟁',
  },
  zh: {
    disputeBanner: '对方已发起争议，请查看。',
    ok: '确定',
    statTrades: '交易',
    statShares: '分享',
    statDisputes: '争议',
  },
  ja: {
    disputeBanner: '相手が紛争を開始しました。確認してください。',
    ok: 'OK',
    statTrades: '取引',
    statShares: '譲り',
    statDisputes: '紛争',
  },
  es: {
    disputeBanner: 'La otra parte abrió una disputa. Revísala.',
    ok: 'OK',
    statTrades: 'Tratos',
    statShares: 'Compartidos',
    statDisputes: 'Disputas',
  },
  pt: {
    disputeBanner: 'A outra parte abriu uma disputa. Confira.',
    ok: 'OK',
    statTrades: 'Negócios',
    statShares: 'Doações',
    statDisputes: 'Disputas',
  },
  fr: {
    disputeBanner: 'L’autre partie a ouvert un litige. Veuillez vérifier.',
    ok: 'OK',
    statTrades: 'Échanges',
    statShares: 'Dons',
    statDisputes: 'Litiges',
  },
  de: {
    disputeBanner: 'Die andere Partei hat einen Streit eröffnet. Bitte prüfen.',
    ok: 'OK',
    statTrades: 'Trades',
    statShares: 'Shares',
    statDisputes: 'Streits',
  },
  id: {
    disputeBanner: 'Pihak lain membuka sengketa. Harap tinjau.',
    ok: 'OK',
    statTrades: 'Transaksi',
    statShares: 'Berbagi',
    statDisputes: 'Sengketa',
  },
  vi: {
    disputeBanner: 'Bên kia đã mở tranh chấp. Vui lòng xem lại.',
    ok: 'OK',
    statTrades: 'Giao dịch',
    statShares: 'Chia sẻ',
    statDisputes: 'Tranh chấp',
  },
  th: {
    disputeBanner: 'อีกฝ่ายเปิดข้อพิพาทแล้ว กรุณาตรวจสอบ',
    ok: 'ตกลง',
    statTrades: 'เทรด',
    statShares: 'แชร์',
    statDisputes: 'ข้อพิพาท',
  },
  hi: {
    disputeBanner: 'दूसरी पक्ष ने विवाद खोला है। कृपया देखें।',
    ok: 'ठीक',
    statTrades: 'लेन-देन',
    statShares: 'शेयर',
    statDisputes: 'विवाद',
  },
  ar: {
    disputeBanner: 'فتح الطرف الآخر نزاعًا. يُرجى المراجعة.',
    ok: 'حسنًا',
    statTrades: 'صفقات',
    statShares: 'مشاركات',
    statDisputes: 'نزاعات',
  },
  ru: {
    disputeBanner: 'Другая сторона открыла спор. Пожалуйста, проверьте.',
    ok: 'OK',
    statTrades: 'Сделки',
    statShares: 'Шеры',
    statDisputes: 'Споры',
  },
  tr: {
    disputeBanner: 'Karşı taraf bir anlaşmazlık açtı. Lütfen inceleyin.',
    ok: 'Tamam',
    statTrades: 'İşlem',
    statShares: 'Paylaşım',
    statDisputes: 'Anlaşmazlık',
  },
  it: {
    disputeBanner: 'L’altra parte ha aperto una controversia. Controlla.',
    ok: 'OK',
    statTrades: 'Scambi',
    statShares: 'Condivisioni',
    statDisputes: 'Controversie',
  },
  pl: {
    disputeBanner: 'Druga strona otworzyła spór. Sprawdź proszę.',
    ok: 'OK',
    statTrades: 'Transakcje',
    statShares: 'Udostępnienia',
    statDisputes: 'Spory',
  },
  nl: {
    disputeBanner: 'De andere partij heeft een geschil geopend. Bekijk het.',
    ok: 'OK',
    statTrades: 'Trades',
    statShares: 'Shares',
    statDisputes: 'Geschillen',
  },
  fil: {
    disputeBanner: 'Nagbukas ng dispute ang kabilang partido. Pakisuri.',
    ok: 'OK',
    statTrades: 'Trades',
    statShares: 'Shares',
    statDisputes: 'Disputes',
  },
  uk: {
    disputeBanner: 'Інша сторона відкрила спір. Перегляньте, будь ласка.',
    ok: 'OK',
    statTrades: 'Угоди',
    statShares: 'Шери',
    statDisputes: 'Суперечки',
  },
  bn: {
    disputeBanner: 'অন্য পক্ষ বিরোধ খুলেছে। অনুগ্রহ করে দেখুন।',
    ok: 'ঠিক আছে',
    statTrades: 'লেনদেন',
    statShares: 'শেয়ার',
    statDisputes: 'বিরোধ',
  },
  ms: {
    disputeBanner: 'Pihak lain membuka pertikaian. Sila semak.',
    ok: 'OK',
    statTrades: 'Dagangan',
    statShares: 'Kongsi',
    statDisputes: 'Pertikaian',
  },
  sw: {
    disputeBanner: 'Upande mwingine umefungua mgogoro. Tafadhali kagua.',
    ok: 'Sawa',
    statTrades: 'Biashara',
    statShares: 'Shiriki',
    statDisputes: 'Migogoro',
  },
  fa: {
    disputeBanner: 'طرف مقابل اختلاف باز کرده است. لطفاً بررسی کنید.',
    ok: 'باشه',
    statTrades: 'معاملات',
    statShares: 'اشتراک',
    statDisputes: 'اختلافات',
  },
  ur: {
    disputeBanner: 'دوسری جانب نے تنازع کھولا ہے۔ براہ کرم دیکھیں۔',
    ok: 'ٹھیک',
    statTrades: 'لین دین',
    statShares: 'شیئرز',
    statDisputes: 'تنازعات',
  },
};

export function commonT(lang: AppLanguage, key: CommonMessageKey): string {
  return COMMON_MESSAGES[lang]?.[key] ?? COMMON_MESSAGES.en[key] ?? key;
}
