/* Auto-generated by scripts/gen-notice-i18n.mjs */
import type { AppLanguage } from '@/utils/languageStorage';

export type NoticeMessageKey =
  | 'noticesTitle'
  | 'loadNoticesFailed'
  | 'loadNoticeFailed'
  | 'noNotices'
  | 'popupNoImage';

const NOTICE_MESSAGES: Record<AppLanguage, Record<NoticeMessageKey, string>> = {
  en: {
    noticesTitle: 'Notices',
    loadNoticesFailed: 'Could not load notices.',
    loadNoticeFailed: 'Could not load this notice.',
    noNotices: 'No notices yet.',
    popupNoImage: 'No image',
  },
  ko: {
    noticesTitle: '공지사항',
    loadNoticesFailed: '공지 목록을 불러오지 못했습니다.',
    loadNoticeFailed: '공지를 불러오지 못했습니다.',
    noNotices: '등록된 공지가 없습니다.',
    popupNoImage: '이미지 없음',
  },
  zh: {
    noticesTitle: '公告',
    loadNoticesFailed: '无法加载公告列表。',
    loadNoticeFailed: '无法加载该公告。',
    noNotices: '暂无公告。',
    popupNoImage: '暂无图片',
  },
  ja: {
    noticesTitle: 'お知らせ',
    loadNoticesFailed: 'お知らせ一覧を読み込めませんでした。',
    loadNoticeFailed: 'お知らせを読み込めませんでした。',
    noNotices: 'お知らせはまだありません。',
    popupNoImage: '画像なし',
  },
  es: {
    noticesTitle: 'Avisos',
    loadNoticesFailed: 'No se pudieron cargar los avisos.',
    loadNoticeFailed: 'No se pudo cargar este aviso.',
    noNotices: 'Aún no hay avisos.',
    popupNoImage: 'Sin imagen',
  },
  pt: {
    noticesTitle: 'Avisos',
    loadNoticesFailed: 'Não foi possível carregar os avisos.',
    loadNoticeFailed: 'Não foi possível carregar este aviso.',
    noNotices: 'Ainda não há avisos.',
    popupNoImage: 'Sem imagem',
  },
  fr: {
    noticesTitle: 'Annonces',
    loadNoticesFailed: 'Impossible de charger les annonces.',
    loadNoticeFailed: 'Impossible de charger cette annonce.',
    noNotices: 'Aucune annonce pour le moment.',
    popupNoImage: 'Aucune image',
  },
  de: {
    noticesTitle: 'Hinweise',
    loadNoticesFailed: 'Hinweise konnten nicht geladen werden.',
    loadNoticeFailed: 'Dieser Hinweis konnte nicht geladen werden.',
    noNotices: 'Noch keine Hinweise.',
    popupNoImage: 'Kein Bild',
  },
  id: {
    noticesTitle: 'Pengumuman',
    loadNoticesFailed: 'Gagal memuat pengumuman.',
    loadNoticeFailed: 'Gagal memuat pengumuman ini.',
    noNotices: 'Belum ada pengumuman.',
    popupNoImage: 'Tidak ada gambar',
  },
  vi: {
    noticesTitle: 'Thông báo',
    loadNoticesFailed: 'Không tải được danh sách thông báo.',
    loadNoticeFailed: 'Không tải được thông báo này.',
    noNotices: 'Chưa có thông báo.',
    popupNoImage: 'Không có ảnh',
  },
  th: {
    noticesTitle: 'ประกาศ',
    loadNoticesFailed: 'โหลดรายการประกาศไม่สำเร็จ',
    loadNoticeFailed: 'โหลดประกาศนี้ไม่สำเร็จ',
    noNotices: 'ยังไม่มีประกาศ',
    popupNoImage: 'ไม่มีรูปภาพ',
  },
  hi: {
    noticesTitle: 'सूचनाएं',
    loadNoticesFailed: 'सूचनाएं लोड नहीं हो सकीं।',
    loadNoticeFailed: 'यह सूचना लोड नहीं हो सकी।',
    noNotices: 'अभी कोई सूचना नहीं।',
    popupNoImage: 'कोई चित्र नहीं',
  },
  ar: {
    noticesTitle: 'الإشعارات',
    loadNoticesFailed: 'تعذّر تحميل الإشعارات.',
    loadNoticeFailed: 'تعذّر تحميل هذا الإشعار.',
    noNotices: 'لا إشعارات بعد.',
    popupNoImage: 'لا توجد صورة',
  },
  ru: {
    noticesTitle: 'Объявления',
    loadNoticesFailed: 'Не удалось загрузить объявления.',
    loadNoticeFailed: 'Не удалось загрузить это объявление.',
    noNotices: 'Пока нет объявлений.',
    popupNoImage: 'Нет изображения',
  },
  tr: {
    noticesTitle: 'Duyurular',
    loadNoticesFailed: 'Duyurular yüklenemedi.',
    loadNoticeFailed: 'Bu duyuru yüklenemedi.',
    noNotices: 'Henüz duyuru yok.',
    popupNoImage: 'Görsel yok',
  },
  it: {
    noticesTitle: 'Avvisi',
    loadNoticesFailed: 'Impossibile caricare gli avvisi.',
    loadNoticeFailed: 'Impossibile caricare questo avviso.',
    noNotices: 'Nessun avviso ancora.',
    popupNoImage: 'Nessuna immagine',
  },
  pl: {
    noticesTitle: 'Ogłoszenia',
    loadNoticesFailed: 'Nie udało się wczytać ogłoszeń.',
    loadNoticeFailed: 'Nie udało się wczytać tego ogłoszenia.',
    noNotices: 'Brak ogłoszeń.',
    popupNoImage: 'Brak obrazu',
  },
  nl: {
    noticesTitle: 'Mededelingen',
    loadNoticesFailed: 'Mededelingen konden niet worden geladen.',
    loadNoticeFailed: 'Deze mededeling kon niet worden geladen.',
    noNotices: 'Nog geen mededelingen.',
    popupNoImage: 'Geen afbeelding',
  },
  fil: {
    noticesTitle: 'Mga abiso',
    loadNoticesFailed: 'Hindi ma-load ang mga abiso.',
    loadNoticeFailed: 'Hindi ma-load ang abisong ito.',
    noNotices: 'Wala pang abiso.',
    popupNoImage: 'Walang larawan',
  },
  uk: {
    noticesTitle: 'Оголошення',
    loadNoticesFailed: 'Не вдалося завантажити оголошення.',
    loadNoticeFailed: 'Не вдалося завантажити це оголошення.',
    noNotices: 'Поки немає оголошень.',
    popupNoImage: 'Немає зображення',
  },
  bn: {
    noticesTitle: 'নোটিশ',
    loadNoticesFailed: 'নোটিশ লোড করা যায়নি।',
    loadNoticeFailed: 'এই নোটিশ লোড করা যায়নি।',
    noNotices: 'এখনও কোনো নোটিশ নেই।',
    popupNoImage: 'কোনো ছবি নেই',
  },
  ms: {
    noticesTitle: 'Notis',
    loadNoticesFailed: 'Tidak dapat muat notis.',
    loadNoticeFailed: 'Tidak dapat muat notis ini.',
    noNotices: 'Belum ada notis.',
    popupNoImage: 'Tiada imej',
  },
  sw: {
    noticesTitle: 'Ilani',
    loadNoticesFailed: 'Imeshindwa kupakia ilani.',
    loadNoticeFailed: 'Imeshindwa kupakia ilani hii.',
    noNotices: 'Bado hakuna ilani.',
    popupNoImage: 'Hakuna picha',
  },
  fa: {
    noticesTitle: 'اطلاعیه‌ها',
    loadNoticesFailed: 'بارگذاری اطلاعیه‌ها ممکن نشد.',
    loadNoticeFailed: 'بارگذاری این اطلاعیه ممکن نشد.',
    noNotices: 'هنوز اطلاعیه‌ای نیست.',
    popupNoImage: 'تصویری نیست',
  },
  ur: {
    noticesTitle: 'اطلاعات',
    loadNoticesFailed: 'اطلاعات لوڈ نہیں ہو سکیں۔',
    loadNoticeFailed: 'یہ اطلاع لوڈ نہیں ہو سکی۔',
    noNotices: 'ابھی کوئی اطلاع نہیں۔',
    popupNoImage: 'کوئی تصویر نہیں',
  },
};

export function noticeT(
  lang: AppLanguage,
  key: NoticeMessageKey,
  vars?: Record<string, string | number>,
): string {
  const raw = NOTICE_MESSAGES[lang]?.[key] ?? NOTICE_MESSAGES.en[key] ?? key;
  if (!vars) return raw;
  return Object.entries(vars).reduce(
    (s, [k, v]) => s.split('{' + k + '}').join(String(v)),
    raw,
  );
}
