/* Auto-generated by scripts/gen-search-i18n.mjs */
import type { AppLanguage } from '@/utils/languageStorage';

export type SearchMessageKey =
  | 'searchTitle'
  | 'searchQueryPh'
  | 'filtersTitle'
  | 'recent'
  | 'suggested'
  | 'noResultsFor';

const SEARCH_MESSAGES: Record<AppLanguage, Record<SearchMessageKey, string>> = {
  en: {
    searchTitle: 'Search',
    searchQueryPh: 'Listing, area, or seller',
    filtersTitle: 'Filters',
    recent: 'Recent',
    suggested: 'Suggested',
    noResultsFor: 'No results for "{q}"',
  },
  ko: {
    searchTitle: '검색',
    searchQueryPh: '상품, 지역, 판매자',
    filtersTitle: '필터',
    recent: '최근',
    suggested: '추천',
    noResultsFor: '"{q}"에 대한 결과가 없습니다',
  },
  zh: {
    searchTitle: '搜索',
    searchQueryPh: '商品、地区或卖家',
    filtersTitle: '筛选',
    recent: '最近',
    suggested: '推荐',
    noResultsFor: '没有 “{q}” 的结果',
  },
  ja: {
    searchTitle: '検索',
    searchQueryPh: '出品・地域・出品者',
    filtersTitle: 'フィルター',
    recent: '最近',
    suggested: 'おすすめ',
    noResultsFor: '「{q}」の結果はありません',
  },
  es: {
    searchTitle: 'Buscar',
    searchQueryPh: 'Anuncio, zona o vendedor',
    filtersTitle: 'Filtros',
    recent: 'Recientes',
    suggested: 'Sugeridos',
    noResultsFor: 'Sin resultados para "{q}"',
  },
  pt: {
    searchTitle: 'Buscar',
    searchQueryPh: 'Anúncio, região ou vendedor',
    filtersTitle: 'Filtros',
    recent: 'Recentes',
    suggested: 'Sugestões',
    noResultsFor: 'Sem resultados para "{q}"',
  },
  fr: {
    searchTitle: 'Recherche',
    searchQueryPh: 'Annonce, zone ou vendeur',
    filtersTitle: 'Filtres',
    recent: 'Récent',
    suggested: 'Suggestions',
    noResultsFor: 'Aucun résultat pour « {q} »',
  },
  de: {
    searchTitle: 'Suche',
    searchQueryPh: 'Anzeige, Region oder Verkäufer',
    filtersTitle: 'Filter',
    recent: 'Zuletzt',
    suggested: 'Vorschläge',
    noResultsFor: 'Keine Ergebnisse für „{q}“',
  },
  id: {
    searchTitle: 'Cari',
    searchQueryPh: 'Listing, wilayah, atau penjual',
    filtersTitle: 'Filter',
    recent: 'Terbaru',
    suggested: 'Saran',
    noResultsFor: 'Tidak ada hasil untuk "{q}"',
  },
  vi: {
    searchTitle: 'Tìm kiếm',
    searchQueryPh: 'Tin đăng, khu vực hoặc người bán',
    filtersTitle: 'Bộ lọc',
    recent: 'Gần đây',
    suggested: 'Gợi ý',
    noResultsFor: 'Không có kết quả cho "{q}"',
  },
  th: {
    searchTitle: 'ค้นหา',
    searchQueryPh: 'ประกาศ พื้นที่ หรือผู้ขาย',
    filtersTitle: 'ตัวกรอง',
    recent: 'ล่าสุด',
    suggested: 'แนะนำ',
    noResultsFor: 'ไม่พบผลลัพธ์สำหรับ "{q}"',
  },
  hi: {
    searchTitle: 'खोज',
    searchQueryPh: 'लिस्टिंग, क्षेत्र या विक्रेता',
    filtersTitle: 'फ़िल्टर',
    recent: 'हाल ही में',
    suggested: 'सुझाए गए',
    noResultsFor: '"{q}" के लिए कोई परिणाम नहीं',
  },
  ar: {
    searchTitle: 'بحث',
    searchQueryPh: 'إعلان أو منطقة أو بائع',
    filtersTitle: 'عوامل التصفية',
    recent: 'الأخيرة',
    suggested: 'مقترحة',
    noResultsFor: 'لا نتائج لـ "{q}"',
  },
  ru: {
    searchTitle: 'Поиск',
    searchQueryPh: 'Объявление, район или продавец',
    filtersTitle: 'Фильтры',
    recent: 'Недавние',
    suggested: 'Рекомендуемое',
    noResultsFor: 'Нет результатов по запросу «{q}»',
  },
  tr: {
    searchTitle: 'Ara',
    searchQueryPh: 'İlan, bölge veya satıcı',
    filtersTitle: 'Filtreler',
    recent: 'Son',
    suggested: 'Önerilen',
    noResultsFor: '"{q}" için sonuç yok',
  },
  it: {
    searchTitle: 'Cerca',
    searchQueryPh: 'Annuncio, zona o venditore',
    filtersTitle: 'Filtri',
    recent: 'Recenti',
    suggested: 'Suggeriti',
    noResultsFor: 'Nessun risultato per "{q}"',
  },
  pl: {
    searchTitle: 'Szukaj',
    searchQueryPh: 'Ogłoszenie, lokalizacja lub sprzedawca',
    filtersTitle: 'Filtry',
    recent: 'Ostatnie',
    suggested: 'Proponowane',
    noResultsFor: 'Brak wyników dla „{q}”',
  },
  nl: {
    searchTitle: 'Zoeken',
    searchQueryPh: 'Advertentie, regio of verkoper',
    filtersTitle: 'Filters',
    recent: 'Recent',
    suggested: 'Suggesties',
    noResultsFor: 'Geen resultaten voor "{q}"',
  },
  fil: {
    searchTitle: 'Maghanap',
    searchQueryPh: 'Listing, area, o seller',
    filtersTitle: 'Mga filter',
    recent: 'Kamakailan',
    suggested: 'Iminumungkahi',
    noResultsFor: 'Walang resulta para sa "{q}"',
  },
  uk: {
    searchTitle: 'Пошук',
    searchQueryPh: 'Оголошення, район або продавець',
    filtersTitle: 'Фільтри',
    recent: 'Нещодавні',
    suggested: 'Пропоновані',
    noResultsFor: 'Немає результатів для «{q}»',
  },
  bn: {
    searchTitle: 'অনুসন্ধান',
    searchQueryPh: 'লিস্টিং, এলাকা বা বিক্রেতা',
    filtersTitle: 'ফিল্টার',
    recent: 'সাম্প্রতিক',
    suggested: 'প্রস্তাবিত',
    noResultsFor: '"{q}" এর কোনো ফলাফল নেই',
  },
  ms: {
    searchTitle: 'Cari',
    searchQueryPh: 'Listing, kawasan atau penjual',
    filtersTitle: 'Penapis',
    recent: 'Terkini',
    suggested: 'Dicadangkan',
    noResultsFor: 'Tiada hasil untuk "{q}"',
  },
  sw: {
    searchTitle: 'Tafuta',
    searchQueryPh: 'Tangazo, eneo au muuzaji',
    filtersTitle: 'Vichujio',
    recent: 'Hivi karibuni',
    suggested: 'Zilizopendekezwa',
    noResultsFor: 'Hakuna matokeo kwa "{q}"',
  },
  fa: {
    searchTitle: 'جستجو',
    searchQueryPh: 'آگهی، منطقه یا فروشنده',
    filtersTitle: 'فیلترها',
    recent: 'اخیر',
    suggested: 'پیشنهادی',
    noResultsFor: 'نتیجه‌ای برای «{q}» نیست',
  },
  ur: {
    searchTitle: 'تلاش',
    searchQueryPh: 'لسٹنگ، علاقہ یا فروخت کنندہ',
    filtersTitle: 'فلٹرز',
    recent: 'حالیہ',
    suggested: 'تجویز کردہ',
    noResultsFor: '"{q}" کے لیے کوئی نتیجہ نہیں',
  },
};

export function searchT(
  lang: AppLanguage,
  key: SearchMessageKey,
  vars?: Record<string, string | number>,
): string {
  const raw = SEARCH_MESSAGES[lang]?.[key] ?? SEARCH_MESSAGES.en[key] ?? key;
  if (!vars) return raw;
  return Object.entries(vars).reduce(
    (s, [k, v]) => s.split('{' + k + '}').join(String(v)),
    raw,
  );
}
